filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.modules:
  - module: mysql
    slowlog:
      enabled: true
      var.paths: ["/var/log/mysql/mysql-slow.log"]

output.logstash:
  hosts: ["http://logstash:5044"]

setup.kibana:
  host: "http://kibana:5601"